version: '3.8'

services:

  web:
    build: .
    image: web
    container_name: web
    ports:
      - 5004:5000
    command: python manage.py run -h 0.0.0.0
    volumes:
      - .:/usr/src/app
    environment:
      - FLASK_DEBUG=1
      - APP_SETTINGS=project.server.config.DevelopmentConfig
      - CELERY_BROKER_URL=redis://:pbd2b9cd7fed64c6cf8405d756c9a6690fbe7c9d8f4165eabeb67ad9a37521bc1@ec2-44-206-18-234.compute-1.amazonaws.com:24829
      - CELERY_RESULT_BACKEND=redis://:pbd2b9cd7fed64c6cf8405d756c9a6690fbe7c9d8f4165eabeb67ad9a37521bc1@ec2-44-206-18-234.compute-1.amazonaws.com:24829
    depends_on:
      - redis

  worker:
    build: .
    command: celery --app project.server.tasks.celery worker --loglevel=info --logfile=project/logs/celery.log
    volumes:
      - .:/usr/src/app
    environment:
      - FLASK_DEBUG=1
      - APP_SETTINGS=project.server.config.DevelopmentConfig
      - CELERY_BROKER_URL=redis://:pbd2b9cd7fed64c6cf8405d756c9a6690fbe7c9d8f4165eabeb67ad9a37521bc1@ec2-44-206-18-234.compute-1.amazonaws.com:24829
      - CELERY_RESULT_BACKEND=redis://:pbd2b9cd7fed64c6cf8405d756c9a6690fbe7c9d8f4165eabeb67ad9a37521bc1@ec2-44-206-18-234.compute-1.amazonaws.com:24829
    depends_on:
      - web
      - redis

  redis:
    image: redis:6-alpine
